### PR TITLE
Update firmware files

### PR DESCRIPTION
**Pull request by Maanush2004**
Pull firmware files of latest update and also add country specific bins

### CODE REVIEW

**Comment by Jleeblanch** [comment]
I have to revert these changes as they actually break wifi.

**Comment by Maanush2004** [comment]
Try this once, use the libs and firmware files from Indian ROM. it contains files for brazil argentina too. maybe as some of the files are not same. Wifi is broken.  I'll provide the specific files you want.

**Comment by Jleeblanch** [comment]
Is wifi not working for you? I've fixed the Mac address issue so it is retained from the stock ROM and doesn't reset (or change) when flashing custom roms. 

I guess I don't see the need to add these additional firmware files if wifi is working fine. Nobody has mentioned any issue beyond the mac address but as I said, that's been fixed.

**Comment by Maanush2004** [comment]
Ok revert it. You sure this commit is causing this?

**Comment by Maanush2004** [comment]
Sorry for the delay now I found the fix for it you need to even change it's
wifi folder I'll make a pull request

**Comment by Maanush2004** [comment]
[etc.zip](https://github.com/Jleeblanch/android_vendor_motorola_athene/files/2385841/etc.zip)
I think those files in the commit are symlinks to files in wifi folder

**Pull request merged**
